### ISSUE TITLE
PyReportJasper : Date Parameter Issue

### ISSUE THREAD

**Issue by shwetaparashar** [acesseonline/pyreportjasper#107]
**Describe the bug**

Issue coming when I am working producing report from python with database connection and parameter
**To Reproduce**
d = datetime.date(2019, 4, 13)
pyreportjasper = PyReportJasper()
pyreportjasper.config(
            input_file,
            output_file,
            db_connection=conn,
            output_formats=["pdf", "rtf"],
            #parameters={'python_version': python_version()},
            parameters={ 'dateStart': d,
                        'dateEnd': d},
            locale='en_US'
        )

**Expected behavior**
       Error fill report: No matching overloads found for java.util.HashMap.put(str,datetime.date), options are:
	public java.lang.Object java.util.HashMap.put(java.lang.Object,java.lang.Object)

 

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.8]
 - Library version [e.g. 2.1.0]
 - Java version [e.g. 15] 
 - JVM [e.g. Oracle]

**Jaspersoft Studio (please complete the following information):**
 - Version [e.g. 6.16.0]

**Additional context**

**Comment by shwetaparashar** [comment]
I am still facing the issue while passing date value as parameter for my jasper report
Please see the below error description
Error fill report: Erro fill internal: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Date (java.lang.String and java.util.Date are in module java.base of loader 'bootstrap')

**Comment by hypnotic-frog** [comment]
Did you find any solutions for this?
