### ISSUE TITLE
 PyReportJasper Function not working on iis

### ISSUE THREAD

**Issue by shwetaparashar** [acesseonline/pyreportjasper#109]
**Describe the bug**
 
project deployed on IIS 

after that I browse the pyReportJasper Compiling method given.
 https://hostname/app/compiling/
Error:
HTTP Error 500.0 - Internal Server Error
C:\inetpub\wwwroot\RPGV2\envRpg\Scripts\python.exe - The FastCGI process exited unexpectedly
**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS : Windows
 - Python version . 3.
 - Library version :pyreportjasper-2.1.2
 - Java version  jdk-16.0.2 
 - JRE : jre1.8.0_291
 - JVM  :sqljdbc_8.2

**Jaspersoft Studio (please complete the following information):**
 - Version [e.g. 6.16.0]

**Additional context**

**Comment by jadsonbr** [comment]
@shwetaparashar 
Take a look at this link, there I believe you can find answers to this python problem with IIS and FastCGI.

[https://stackoverflow.com/questions/60043072/python-exe-the-fastcgi-process-exited-unexpectedly](https://stackoverflow.com/questions/60043072/python-exe-the-fastcgi-process-exited-unexpectedly)
