### ISSUE TITLE
Please, I neeed help with this error: Error fill report: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly

### ISSUE THREAD

**Issue by mantfacil** [acesseonline/pyreportjasper#117]
**Describe the bug**
I'm working with Django and your package for the first time.

I'm wanting to launch a report made with jaspersoft from Django. When the __init__ method of the Report class is executed, I get the following error: **'Error fill report: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly. '**

I understand that the JAVA_HOME is well configured; since I have executed the run.py file from this repository **_https://github.com/acesseonline/exemples_report_** and the pdf file is generated correctly.

On the other hand, I wanted to set the path where the jvm is located in the jvm_classpath parameter, but when it reaches the method that I mention above this value arrives empty.

**Expected behavior**
In this first step, I need the pdf report to be saved in a directory.

**Screenshots**
This is my Django code

![Django](https://user-images.githubusercontent.com/77692806/144670590-ccf0d4c6-eb38-4e5a-9190-adf5ad96bfac.PNG)

This is where I have my jvm file hosted
![Java](https://user-images.githubusercontent.com/77692806/144671025-41a7785a-029b-4863-8b11-a8515b6b4157.PNG)

This is the Django error
![django_error](https://user-images.githubusercontent.com/77692806/144671803-59af2bf6-de24-4b7f-ad3d-f3db318d0dcc.PNG)
![Captura](https://user-images.githubusercontent.com/77692806/144672208-4d702dcb-c370-49d2-b7d1-3f10324cdf60.PNG)

And this is my JAVA_HOME
![JAVA_HOME](https://user-images.githubusercontent.com/77692806/144671206-9dfc62f3-7d0e-4c35-86f8-c8c5db77fd89.PNG)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Python version 3.9
 - Library version 2.1.2
 - Java version 11.2
 - JVM Oracle
- Django version 3.2.4
**Jaspersoft Studio (please complete the following information):**
 - Version 6.18.1

**Additional context**
This is probably not a bug in your package and if it is a bad configuration on my part because it is the first time I use it, but I can not find another way to communicate with you, other than this.

**Comment by jadsonbr** [comment]
Note that if you build for a 32-bit Python, make sure to also install a 32-bit JDK. Accordingly, for a 64-bit Python, you will need a 64-bit JDK.

```bash
SET JDK_HOME=<path to the JDK installation directory>
SET JAVA_HOME=%JDK_HOME%
SET PATH=%JDK_HOME%\jre\bin\server;%PATH%
```


If the error persists:

Fix this by adding the path to the Java VM shared library (`jvm.dll`) to the `PATH` environment variable:

**Comment by mantfacil** [comment]
Configuring what you mention and adjusting the connection settings to what I show you below, it worked.

![conn](https://user-images.githubusercontent.com/77692806/145061835-eefb34db-e967-436b-8a83-bb86c9b1ba9e.PNG)

I take this opportunity to ask you, during the execution of the program this appears:
![Captura](https://user-images.githubusercontent.com/77692806/145062552-49e13d0c-9053-45e9-a7aa-d833d6a0d879.PNG)

Is there a possibility to remove it?

**Comment by jadsonbr** [comment]
Is it preventing you from generating the report?
To remove this log just configure log4j

**Comment by mantfacil** [comment]
No, the report is generated ok. 
Nothing more than the first time it is generated, it takes about 4/5 seconds; then the generation is fast.

The log4j configuration from where should I do it? because it is not something i have installed.

**Comment by jadsonbr** [comment]
It is necessary to add `-J-Dlog4j.configuration=file:/C:/log4j.properties` to the VM startup, but today we don't have a parameter to pass this information.

Please feel free to help us with this contribution. Follows the line where the initialization takes place.
https://github.com/acesseonline/pyreportjasper/blob/master/pyreportjasper/report.py#L40

**Comment by jadsonbr** [comment]
About time, if it is the first time you run the code, it will certainly take a little longer to be able to initialize the VM, the next ones will be faster because the VM has already been initialized.
