### ISSUE TITLE
Pass array as a parameter

### ISSUE THREAD

**Issue by ewu-tarun** [acesseonline/pyreportjasper#122]
Is there any way to pass array to the parameter objects?

Suppose I have dynamic JSON like

```
 temp = {
        "name": "test",
        "contacts": {
            "person": [
                {
                    "name": "ETHAN",
                    "street": "Street 1",
                    "city": "Fairfax",
                    "phone": "+1 (415) 111-1111"
                },
                {
                    "name": "CALEB",
                    "street": "Street 2",
                    "city": "San Francisco",
                    "phone": "+1 (415) 222-2222"
                },
                {
                    "name": "WILLIAM",
                    "street": "Street 2",
                    "city": "Paradise City",
                    "phone": "+1 (415) 333-3333"
                }
            ]
        }
    }
```

so i want to pass this json as a parameter. how to do this?

**Comment by TarunDas005** [comment]
@jadsonbr could you please give me a suggestions?

**Comment by jadsonbr** [comment]
Shouldn't this be a datasource?

**Comment by hypnotic-frog** [comment]
> Shouldn't this be a datasource?

Probably on this case, but it has not to be.  Jasper allows collections parameters, but even passing an array of int primitives to params gives 
`Error fill report: No matching overloads found for java.util.HashMap.put(str,list)`

**Comment by jadsonbr** [comment]
Currently, data sent as parameters to the report must be of type string and converted to their appropriate types within the report. It is possible to send the correct type but you will have to do this using the jpype library to interpret the correct type within python to be sent to the java library

[JPype types](https://jpype.readthedocs.io/en/latest/userguide.html#jpype-types)

**Comment by jadsonbr** [comment]
Closed due to lack of interaction.
