### ISSUE TITLE
Error in libray ClassUtils

### ISSUE THREAD

**Issue by aachiary** [acesseonline/pyreportjasper#125]
Hi, how are you?? My name is Andres.
I'm getting an error when I process a report. I can get the PDF anyway but I wanted to know if there is anything I can do so I don't get this error message or, at least, hide it.
Thanks!

The error message I get is:
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.jasperreports.engine.util.ClassUtils (file:/C:/Users/Andy/AppData/Local/Programs/Python/Python39/Lib/site-packages/pyreportjasper/libs/jasperreports-6.16.0.jar) to constructor com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl()
WARNING: Please consider reporting this to the maintainers of net.sf.jasperreports.engine.util.ClassUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jadsonbr** [comment]
We are working to set a default configuration for the log4j2 file and consequently the message that the file does not exist will disappear.

**Comment by aachiary** [comment]
Thanks for the reply!
