### ISSUE TITLE
Script stops at "process_report"

### ISSUE THREAD

**Issue by PhunkyBob** [acesseonline/pyreportjasper#126]
**Describe the bug**
I try the exemple found in https://github.com/acesseonline/exemples_report
At `pyreportjasper.process_report()`, my program stops without error. No PDF file is produced.

**To Reproduce**
1. `git clone https://github.com/acesseonline/exemples_report.git`
2. With VSCode, run debug on `run.py` with break point on line 33 (`pyreportjasper.process_report()`). 
3. When breakpoint reached, "Step". 

**Expected behavior**
Program continues to next line (`output_file = output_file + '.pdf'`).

**Actual behavior**
Program stops, without any warning. 

**Desktop:**
 - OS: Windows 11
 - Python 3.10.5 (32 bits)
 - pyreportjasper version 2.1.2
 - openjdk 17.0.3 2022-04-19 (32 bits)
 - JVM Amazon Corretto

**Jaspersoft Studio:**
 - TIBCO Jaspersoft® Studio 6.19.1 - Visual Designer for JasperReports 6.19.1.

**Comment by jadsonbr** [comment]
**Debug stop**

![image](https://user-images.githubusercontent.com/10354607/178787618-8623a0f2-399a-48cd-b805-9d7bcac23a62.png)

**Report generated**

![image](https://user-images.githubusercontent.com/10354607/178788177-37f660fb-7407-4159-b955-fa9fa556cc85.png)

**Comment by PhunkyBob** [comment]
Unfortunatly, not for me... 
It stops without any error.

**Comment by jadsonbr** [comment]
What is the output in the terminal?

**Comment by PhunkyBob** [comment]
Nothing.
It stops as if the script finished at this line.

**Comment by jadsonbr** [comment]
More what was displayed in the terminal, regardless of whether it stopped at the break point or not, it shows execution data in the terminal what is it displaying?

**Comment by PankajLal99** [comment]
@jadsonbr same issue for me  

code doesn't move forward after process_report
but for me its works if you put it in a standalone script 
I will suggest you run the function without django just like the basic script. 

It doesn't work in django it just stops couldn't move further process_report()
 
![Screenshot 2023-06-19 at 11 12 38 AM](https://github.com/acesseonline/pyreportjasper/assets/47896858/4718c389-dd59-476f-98bb-6ce0f4f7b8f7)

**Comment by jadsonbr** [comment]
Try updating the library version.

**Comment by PhunkyBob** [comment]
pyreportjasper==2.1.3
+
Python 3.11.7
+ 
Corretto 21
=
It works!
