### ISSUE TITLE
 Error fill report: input file: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'isTrue': Instantiation of bean failed; nested exception is java.lang.NoSuchMethodError: 'java.lang.Object org.springframework.util.ObjectUtils.unwrapOptional(java.lang.Object)' is not a valid jrxml file:

### ISSUE THREAD

**Issue by kabiio** [acesseonline/pyreportjasper#133]
Linux rever-centos7-prod-sin 3.10.0-1160.21.1.el7.x86_64 #1 SMP Tue Mar 16 18:28:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Python python:3.7.14
Library version pyreportjasper 2.1.2
Java version java version: " jdk-11.0.16"
JVM : mysql server

**Comment by jadsonbr** [comment]
The input file extension `.jrxml` are you sure it is a valid file? Try to open this file through JasperReport and try to compile to see what the output is before running the library and tell us the result.

**Comment by kabiio** [comment]
sure @jadsonbr, same .jrxml file working in my windows machine once i run in my linux server occur this error

**Comment by kabiio** [comment]
@jadsonbr, using pyreportjasper==2.1.2 
![Screenshot 2022-11-21 105003](https://user-images.githubusercontent.com/91416401/202971475-ee118147-527e-49a0-8f57-08822c0ca086.png) , the same .jrxml file working fine in my Jasper Report studio and my window system pyreportjasper, this same I try in Linux server occurred this error.

**Comment by kabiio** [comment]
@jadsonbr 
 how to install pyreportjasper on Linux any path to add docker file?

**Comment by jadsonbr** [comment]
Remove the current installation and install via git to use a compiled version for your operating system and try again.

```pip install git+https://github.com/acesseonline/pyreportjasper@master#egg=pyreportjasper```

**Comment by kabiio** [comment]
thankyou @jadsonbr, After installing from git our problem was solved
