### ISSUE TITLE
Error fill report: Erro fill internal: java.lang.ClassNotFoundException: com.simba.googlebigquery.jdbc.Driver

### ISSUE THREAD

**Issue by yan286** [acesseonline/pyreportjasper#134]
Can i know if Google Big query is supported?
i am using the configuration as follow

```
'driver': 'generic',
'jdbc_url': 'jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId={project_id};OAuthType=0;OAuthServiceAcctEmail={email};OAuthPvtKeyPath={path_to_p12_dir};',
'jdbc_driver': 'com.simba.googlebigquery.jdbc.Driver',
'jdbc_dir': path_to_all_jdbc_jar_dir,
```
And it throw the exception below. Thanks for the help
NameError: Error fill report: Erro fill internal: java.lang.ClassNotFoundException: `com.simba.googlebigquery.jdbc.Driver`

**Comment by jadsonbr** [comment]
It has not been tested but I believe it works. The error specified above is that I don't find the class informed `jdbc_driver` within the jars specified in the folder informed in the parameter `jdbc_dir`. Are you sure that the jdbc jar is inside the folder informed in the `jdbc_dir` parameter. 
And the error message is saying that it did not find `com.simba.googlebigquery.jdbc42.Driver` and the parameter `jdbc_driver` is informed `com.simba.googlebigquery.jdbc.Driver` according to the code you sent.


[https://community.jaspersoft.com/project/google-bigquery-connector](https://community.jaspersoft.com/project/google-bigquery-connector)

**Comment by yan286** [comment]
ya my bad i meant `com.simba.googlebigquery.jdbc.Driver` its typo. But i am sure that **all** the jar file needed present in the directory specified in `jdbc_dir` parameter. But according to your finding the error specified is that the jar file is as per what i pass in `jdbc_driver` not present thats why it throw this error or this `com.simba.googlebigquery.jdbc.Driver` is not present at all? Last but not least, if i were to connect to pyreportjasper using jdbc url is the config stated above is correct?

**Comment by jadsonbr** [comment]
I'm not familiar with the JDBC connection URL for Google BigQuery, but if it's correct, it should work. If everything goes well, could you let us know? It will help us enrich our documentation with other types of connections.

**Comment by yan286** [comment]
no, its not working and i have moved to other solution
