### ISSUE TITLE
How to handle images

### ISSUE THREAD

**Issue by 1271513767** [acesseonline/pyreportjasper#145]
How to handle images, local images, or online images

**Comment by jadsonbr** [comment]
[Initiate a discussion](https://github.com/acesseonline/pyreportjasper/discussions/new/choose) on the subject. The issue will be closed as it pertains to error reporting and feature requests.

[Here you can see an example of image usage.](https://replit.com/@JadsonRibeiro/with-image-pyreportjasper)
