### ISSUE TITLE
PDF report generated from python using pyreportjasper is different from JasperSoft Studio

### ISSUE THREAD

**Issue by DTDKCWong** [acesseonline/pyreportjasper#149]
I used Javasoft Studio to design a report by using JSON as the data source. Doing some formatting on the fields as below:

![image](https://github.com/acesseonline/pyreportjasper/assets/111565822/82914ff7-47c6-4bb9-a69a-5fdc735e9121)

I then wrote a Python program to use PyReportJasper to generate the PDF report by using the same jrxml file as I used in the Javasoft Studio. However, the output doesn't match the output in Studio. The format is messy.

![image](https://github.com/acesseonline/pyreportjasper/assets/111565822/1fa7508c-32e6-4fa9-83c7-67bd8972b4fc)

The comma of the thousand separator is showed as a full stop. The % format is totally a mess.

I use Jaspersoft Studio 6.20.6, PyReportJasper 2.1.2 

Any one has come across the same issue?

KC

**Comment by jadsonbr** [comment]
@DTDKCWong 

> I used Javasoft Studio to design a report by using JSON as the data source. Doing some formatting on the fields as below:
> 
> ![image](https://private-user-images.githubusercontent.com/111565822/283320761-82914ff7-47c6-4bb9-a69a-5fdc735e9121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDcyODEsIm5iZiI6MTcwMzg0Njk4MSwicGF0aCI6Ii8xMTE1NjU4MjIvMjgzMzIwNzYxLTgyOTE0ZmY3LTQ3YzYtNGJiOS1hNjlhLTVmZGM3MzVlOTEyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxMDQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZjNiZGYyYWMyN2EzYzQ1NDZiNjJiNzFmYzdhYjViZjM4ZTMzNjNiOTM0YTVlNDAxMTgzZTczNzFhZGEyMzhmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g83AZq2AT6jJCX4QGp7UJ7wKD0bZW9ti982NX7O6Yo0)
> 
> I then wrote a Python program to use PyReportJasper to generate the PDF report by using the same jrxml file as I used in the Javasoft Studio. However, the output doesn't match the output in Studio. The format is messy.
> 
> ![image](https://private-user-images.githubusercontent.com/111565822/283322395-1fa7508c-32e6-4fa9-83c7-67bd8972b4fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDcyODEsIm5iZiI6MTcwMzg0Njk4MSwicGF0aCI6Ii8xMTE1NjU4MjIvMjgzMzIyMzk1LTFmYTc1MDhjLTMyZTYtNGZhOS04M2M3LTY3YmQ4OTcyYjRmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxMDQ5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTY4ODFkMGQ4NDhmYTVlZjBhMDM4OTNkZDQ3OGQ2MWZjNzk5ZDMzMzkxMGQwZDhmYjQ4NGI1MTUyM2NiNTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.etd5tmcIOwHbq6HO59XGahzauCtauqWi8apwHHWQHm0)
> 
> The comma of the thousand separator is showed as a full stop. The % format is totally a mess.
> 
> I use Jaspersoft Studio 6.20.6, PyReportJasper 2.1.2
> 
> Any one has come across the same issue?
> 
> KC

 I believe that when you tested it, you hadn't saved the .jrxml file in Jaspersoft Studio because, looking at the attached image, it still has the * in the file. Also, try using the new version 2.1.3.

**Comment by jadsonbr** [comment]
> can you share the code? Because I am getting error in this code :import os
> 
> ```python
> #import pyreportjasper
> #from io import StringIO
> #from pyjasper.jasperpy import JasperPy
> from pyjasper.jasperpy import JasperPy
> 
> def compile_and_process():
>     # Compilation
>     input_file = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'C:\\Users\\Report_20102023.jrxml')
>     print(input_file)
>     jasper = JasperPy()
>     compiled_file = jasper.compile(input_file)
> 
>     # Processing
>     output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'output')
>     jasper.process(compiled_file, output=output_dir, format_list=["pdf", "rtf"])
> 
> if __name__ == "__main__":
>     compile_and_process()
>     
> ```
> 
> error : Import "pyjasper.jasperpy" could not be resolved


@rawsid11 
It seems like your imports are commented out. Another issue is that the library imports themselves do not correspond to `pyreportjasper`.

**Comment by jadsonbr** [comment]
Closed due to lack of engagement.
