### ISSUE TITLE
Shallow Documentation

### ISSUE THREAD

**Issue by fradrick** [acesseonline/pyreportjasper#158]
There is no clarity when dealing with data that already exists in memory.

for example I have django model like so:
class User(models.Model):
     first_name,
     last_name

then I fetch my data like so:

user  = User.objects.all()

The closest solution I saw is db_connection but this feature requires a whole lot of other attributes not relevant. All I want is to pass data to the method and then it given me results.

How exactly should we just pass data.

**Comment by jadsonbr** [comment]
You can do this directly via the database by querying the report and passing the connection data as parameters to the library. Alternatively, you can use JSON with the ORM query data, convert it to JSON bytes, and pass these data in the `data_file` parameter. Here is a model of how to do it

```python
# -*- coding: utf-8 -*-
import os
import json
from pyreportjasper import PyReportJasper


def json_to_pdf():
	REPORTS_DIR = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'reports')
	input_file = os.path.join(REPORTS_DIR, 'users.jrxml')
	output_file = os.path.join(REPORTS_DIR, 'output_dir')

	# "Here is where the data processing for sending to the report will take place.
	_all_data = User.objects.all()
	json_data = json.dumps({
		'users':[{'name': reporter.full_name, 'profile': reporter.profile} for reporter in _all_data]
	})
	bytes_data = json_data.encode('utf-8')

	conn = {
	  'driver': 'json',
	  'data_file': bytes_data,
	  'json_query': 'users'
	}
	pyreportjasper = PyReportJasper()
	self.pyreportjasper.config(
		input_file,
		output_file,
		output_formats=["pdf"],
		db_connection=conn
	)
	self.pyreportjasper.process_report()
	print('Result is the file below.')
	print(output_file + '.pdf')


json_to_pdf()
```

As this is not a problem here, I recommend opening a discussion if needed. [Open new discussion](https://github.com/acesseonline/pyreportjasper/discussions/new/choose)

**Comment by fradrick** [comment]
Wellnoted, thank you for prompt response, will try to implement this and give feedback.

**Comment by fradrick** [comment]
I have finally modified my code to this. I am realising that the code is doing all the validations without any problems. However it contiuosly run doesnt finish execution. No error is being thrown. 
what could be the problem here? There problem should be somwhere inside the process_report() method

````
def _export_to_excel(self):
        REPORTS_DIR = os.path.abspath(os.path.dirname(__file__))
        batches = Batch.objects.all()[:50] # get the first 50 records
        json_data = json.dumps({
            "batches": [{'id': str(batch.id)} for batch in batches]
        })
        bytes_data = json_data.encode('utf-8')


        conn = {
            'driver': 'json',
            'data_file': bytes_data,
            'json_query': 'batches'
        }

        input_file = os.path.join(REPORTS_DIR, 'batches.jrxml')
        output_file = os.path.join(REPORTS_DIR, 'batches')

        pyreportjasper = PyReportJasper()
        pyreportjasper.config(
            input_file,
            output_file,
            output_formats=['pdf'],
            db_connection=conn,
        )
        print("AFTER_CONFIG")  # this stage is being reached
        pyreportjasper.process_report()
        print('Result is the file below.') # This stage cant be reached
        print(output_file+'.pdf')

        return

**Comment by jadsonbr** [comment]
What version of the library and Java are you using? And what is the operating system and architecture?
Could you also send a screenshot of the terminal showing the execution of your _export_to_excel() function?

**Comment by fradrick** [comment]
> What version of the library and Java are you using? And what is the operating system and architecture? Could you also send a screenshot of the terminal showing the execution of your _export_to_excel() function?

macOS Sonoma v: 14.2.1
Python: 3.10.13
pyreportjasper:  2.1.3

Error occurred during initialization of VM
java.lang.UnsupportedClassVersionError: org/update4j/DynamicClassLoader has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by jadsonbr** [comment]
And what is the Java version?

**Comment by fradrick** [comment]
openjdk version "1.8.0_392"

**Comment by jadsonbr** [comment]
The library requires Java 9 or higher, as stated in the readme

**Comment by fradrick** [comment]
Well I upgraded my java to v21
Using:
python: 3.6.8
Django: 2.2.6
OS: Centos 7

I have downgraded my pyreportjasper to 2.1.2 which is compatible with the python version

my code is:
`json_data = json.dumps({
            "batches": [{'id': str(batch.id)} for batch in self._queryset]
        })
        bytes_data = json_data.encode('utf-8')

        conn = {
            'driver': 'json',
            'data_file': bytes_data,
            'json_query': 'batches'
        }

        REPORTS_DIR = os.path.join(os.path.abspath(os.path.dirname(__file__)))
        input_file = os.path.join(REPORTS_DIR, 'batches.jrxml')
        output_file = os.path.join(REPORTS_DIR, out_put_file_name.rsplit('.', 1)[0])

        pyreportjasper = PyReportJasper()
        pyreportjasper.config(
            input_file,
            output_file,
            output_formats=output_formats,
            db_connection=conn
        )
        pyreportjasper.process_report()`

Now I am getting this error:

**Comment by jadsonbr** [comment]
Running normally, please check your code.

![image](https://github.com/acesseonline/pyreportjasper/assets/10354607/1b6115f4-c1a9-4481-ac7f-8f5453b894f5)

**Comment by fradrick** [comment]
Well it should have been some issues with my code. All is fine and working properly now.

**Comment by hardy9am** [comment]
Same Problem here. The execution won't stop on macOS with Java 9.0.4 or OpenJDK 21 with both python3.9/3.11

```bash
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.jasperreports.engine.util.ClassUtils (file:******/new_venv/lib/python3.9/site-packages/pyreportjasper/libs/jasperreports-6.20.6.jar) to constructor com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl()
WARNING: Please consider reporting this to the maintainers of net.sf.jasperreports.engine.util.ClassUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The script would stop here and can't get a result.
