### ISSUE TITLE
Error: Unable to initialize main class de.cenote.jasperstarter.App

### ISSUE THREAD

**Issue by tam4it** [acesseonline/pyreportjasper#70]
Hi - When I call process method to run hello_world.jrxml file to export into pdf format in spyder env, I get this error

...\pyreportjasper-1.0.3-py3.7.egg\pyreportjasper\jasperpy.py", line 201, in execute
    raise NameError('Your report has an error and couldn\'t be processed!\n' + e.stderr)

NameError: Your report has an error and couldn't be processed!
Error: Unable to initialize main class de.cenote.jasperstarter.App
Caused by: java.lang.NoClassDefFoundError: net/sf/jasperreports/engine/JRException

Can any one assist to figure this error, I'm new to your lib and followed your requirement - still nogo

Thanks

**Comment by jadsonbr** [comment]
@tam4it  I advise you to install the newest version (2.0.2) through github and do it through the documentation to test

**Comment by tam4it** [comment]
thanks jadsonbr - uninstalled old version and re-installed new version 2.0.2, now i get this error.  I tried to pip install jpyutil but i get ERROR: No matching distribution found for jpyutil.  thanks

  from .jasperpy import JasperPy
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreportjasper-2.0.2-py3.7.egg\pyreportjasper\jasperpy.py", line 13, in <module>
    import jpyutil
ModuleNotFoundError: No module named 'jpyutil'

**Comment by jadsonbr** [comment]
@tam4it Try installing jpy from git too
```
pip install git+https://github.com/bcdev/jpy@master#egg=jpy
```

**Comment by tam4it** [comment]
Great @jadsonbr  - jpy module installed successfully after several attempts - Successfully installed jpy-0.10.0.dev1
but now, a new error has occurred - 

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyreportjasper-2.0.2-py3.7.egg\pyreportjasper\jasperpy.py", line 58, in __init__
    self.jvReport = jpy.get_type('de.cenote.jasperstarter.Report')
ValueError: Java class 'de.cenote.jasperstarter.Report' not found

sorry to bother you, I really want to use your libs or may be I've to find alternate way to export pdf for each parameter input out of jrxml

**Comment by jadsonbr** [comment]
This version jpy-0.10.0.dev1 is not very good, I advise you to use the version of the conda, follow the link.
In the new version jpy will be replaced by jpype which is much less problematic

https://anaconda.org/terradue/jpy

**Comment by Jpatel2408** [comment]
hello, I m working with this library.  and using your(@jadsonbr ) Django example but when I try to pass the parameter it getting an error like this:
NameError at /report/generate/
Your report has an error and couldn \'t be processed!\ Try to output the command using the attribute `command;` and run it manually in the console!

This is method call :
jasper = JasperPy()
jasper.process(template, output_file=output, format_list=["pdf"],  parameters={'name':'jay'})

**Comment by jadsonbr** [comment]
@Jpatel2408 What values are being passed to input_file and output_file? And which version of the library are you using?

**Comment by jadsonbr** [comment]
Please upgrade to the latest version.
