### ISSUE TITLE
No data from database in report

### ISSUE THREAD

**Issue by VretTech** [acesseonline/pyreportjasper#76]
I think I configured the database connection properly, everything runs, but the report shows no data. Could you please provide a working db config example for a mysql database?

Code example:

`def advanced_example_using_database():
   REPORTS_DIR = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'reports')
  
   input_file = os.path.join(REPORTS_DIR, 'test_ea.jrxml')
   output_file = os.path.join(REPORTS_DIR, 'hello_world')
   conn = {

   'dbtype': 'mysql',
   'host': 'myhost',
   'user': 'myuser',
   'passwd': 'mypass',
       'port': 'myport',

   }
   pyreportjasper = PyReportJasper()
   pyreportjasper.config(
     input_file,
     output_file,
     db_connection=conn,
     output_formats=["pdf", "rtf"],
     parameters={'python_version': python_version()},
     locale='en_US'
   )
   pyreportjasper.process_report()`

Any help is really appreciated,
Cheers,
Fred.

**Comment by jadsonbr** [comment]
You should download the jdbc connection .jar for mysql and pass the connection parameters. Everything is very simple and the documentation tells you what each parameter means.

[Documentation link](https://pyreportjasper.readthedocs.io/en/latest/api.html#class-pyreportjasper)

[Link download jar mysql jdbc](https://dev.mysql.com/downloads/connector/j/)

**Basic example:**
```python
# -*- coding: utf-8 -*-
import os
from platform import python_version
from pyreportjasper import PyReportJasper

def advanced_example_using_database():
   REPORTS_DIR = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'reports')
   input_file = os.path.join(REPORTS_DIR, 'hello_world.jrxml')
   output_file = os.path.join(REPORTS_DIR, 'hello_world')
   conn = {
     'driver': 'postgres',
     'username': 'user_bd',
     'password': '25f77c8d82f37fa930',
     'host': 'localhost',
     'database': 'my_bd',
     'port': '3306'
     'jdbc_dir': '<path>/mysql-connector-java-8.0.22.jar'
   }
   pyreportjasper = PyReportJasper()
   pyreportjasper.config(
     input_file,
     output_file,
     db_connection=conn,
     output_formats=["pdf"],
     locale='en_US'
   )
   pyreportjasper.process_report()
```

This does not mean that this example has all the information you need. It goes according to your database settings. In the api documentation you will find all the options available for use.
