### ISSUE TITLE
NameError: Error fill report: Erro fill internal: net.sf.jasperreports.engine.JRException: Resource not found

### ISSUE THREAD

**Issue by raviselva4** [acesseonline/pyreportjasper#77]
**Describe the bug**
When I try to run a report with sub report the code throws the error saying "Resource not found" at publicaton_subreport.jasper.  Looks like it's not finding the file because of missing file path.  

How do I pass the sub report path when I call process_report()?

Here is the code what I am passing:

jasper = PyReportJasper()
jasper.config(
    input_file,
    output_file,
    db_connection=conn,
    output_formats=["pdf"],
    parameters={},
    locale='en_US',
    resource=resource_dir
)
jasper.process_report()

I am passing the sub-report file path to the resource_dir variable but its not working.  

(Note: It worked when I include the file path for the sub report on the main report jrxml file)

Thanks,
Ravi

**Comment by jadsonbr** [comment]
We released a new version 2.1.2 with the feature implementation. Below is a link with a subreport test.
[https://repl.it/@JadsonRibeiro/sub-report-pyreportjasper#main.py](https://repl.it/@JadsonRibeiro/sub-report-pyreportjasper#main.py)
