### ISSUE TITLE
Bold font is not printing in pdf using json file as data source

### ISSUE THREAD

**Issue by gholakemohit** [acesseonline/pyreportjasper#79]
I am using json file as data source.

In jasper report, there are some bold font element which are compiling in correct way in jasper studio.

But while generating pdf using pyjasperreport library bold font element are not bold, they converted to normal font. 

How to solve this problem

**Comment by jadsonbr** [comment]
Answer the questions below in order to better answer you.


**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Python version [e.g. 3.8]
 - Library version [e.g. 2.1.0]
 - Java version [e.g. 15] 
 - JVM [e.g. Oracle]

**Jaspersoft Studio (please complete the following information):**
 - Version [e.g. 6.16.0]

**Comment by gholakemohit** [comment]
os windows 10
python 3.9
library 2.1.2
java 15.0.2

jvm java version "15.0.2" 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)

jaspersoft 6.16.0
font calibri

**Comment by jadsonbr** [comment]
Create a font extension in Jasper Studio. [Click here and see how to do it.](https://community.jaspersoft.com/documentation/tibco-jaspersoft-studio-user-guide/v640/fonts)

Export this extension. You will get .jar for this export. And after that add it as a `resource` in pyreportjasper.

Even in JasperStudio if you are exporting to PDF and do not have this extension it will not work. Only when previewing within JasperStudio will you get the expected result. For the correct export it is necessary to add the font.

**Comment by gholakemohit** [comment]
how to add it as a resource?

**Comment by gholakemohit** [comment]
i have done the process. but getting below error.
net.sf.jasperreports.engine.util.JRFontNotFoundException: Font "Calibri" is not available to the JVM. See the Javadoc for more details.

**Comment by jadsonbr** [comment]
You must be doing something wrong.

Everything is working properly. Here is an example of a report I just generated using the Calibri font and the pyreportjasper library. 


[calibri.pdf](https://github.com/acesseonline/pyreportjasper/files/5904951/calibri.pdf)

**Comment by gholakemohit** [comment]
how to add it as a resource?
in code or location?

**Comment by jadsonbr** [comment]
Just put the directory where the .jar is located.

```python
pyreportjasper.config(
      input_file,
      output_file,
      output_formats=["pdf"],
      db_connection={},
      resource=RESOURCES_DIR
   )
```

**Comment by gholakemohit** [comment]
not working.
let it be.
we have skip this font thing now.
thanks by the way using your library for my project.
