### ISSUE TITLE
NameError: Error fill report: Erro fill internal: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by gholakemohit** [acesseonline/pyreportjasper#83]
My program will fetch data from redshift database and generates json file and Using json file will create pdf in single python script.

For bigger data size json created successfully, but pdf generation shows below error.

pyreportjasper NameError: Error fill report: Erro fill internal: java.lang.OutOfMemoryError: Java heap space

**Comment by gholakemohit** [comment]
Can I solve this issue using multithreading.

**Comment by jadsonbr** [comment]
Make sure you have enough memory to process your file. If you still have the error, try to increase the maximum memory that the jvm can use, for this you have an example below.

[https://repl.it/@JadsonRibeiro/jvmmax-mem-pyreportjasper#main.py](https://repl.it/@JadsonRibeiro/jvmmax-mem-pyreportjasper#main.py)

**Comment by gholakemohit** [comment]
ok
thanks
