### ISSUE TITLE
AttributeError: 'function' object has no attribute 'input'

### ISSUE THREAD

**Issue by tam4it** [acesseonline/pyreportjasper#84]
Hi there - I get this error when I used one of your 'Hello World' example https://pyreportjasper.readthedocs.io/en/master/userguide.html#the-hello-world-example compiling() and processing() in spyder env
File "C:\Users\tazeez\AppData\Local\Continuum\anaconda3\lib\site-packages\pyreportjasper\pyreportjasper.py", line 109, in compile
    if os.path.isfile(self.config.input):
AttributeError: 'function' object has no attribute 'input'

I was using the old deprecated class obj JasperPy and it worked well but no luck with the new version.  looks like some of them are changed.

Thanks

**Comment by jadsonbr** [comment]
@tam4it  Below is a link with several examples

[https://repl.it/@JadsonRibeiro](https://repl.it/@JadsonRibeiro)
