### ISSUE TITLE
How to give a List variable from CSV ?

### ISSUE THREAD

**Issue by stofix** [acesseonline/pyreportjasper#87]
I would like to use a subreport and i have to pass a variable of type of java.util.List.
How can I do ?

Many tests give me this error :
NameError: Error fill report: Erro fill internal: net.sf.jasperreports.engine.JRException: Unable to get value for CSV field "variable" of class java.util.List.

**Comment by jadsonbr** [comment]
Follow an example using CSV
[https://repl.it/@JadsonRibeiro/csv-report-pyreportjasper#main.py](https://repl.it/@JadsonRibeiro/csv-report-pyreportjasper#main.py)

Follow an example using subreport
[https://repl.it/@JadsonRibeiro/sub-report-pyreportjasper#main.py](https://repl.it/@JadsonRibeiro/sub-report-pyreportjasper#main.py)
