### ISSUE TITLE
Error fill report: Erro fill internal: java.lang.NullPointerException

### ISSUE THREAD

**Issue by arif-rahman-cse** [acesseonline/pyreportjasper#91]
I am getting this error when try to connect pyreportjasper  to database . I am using MSSQL Server 2016 , JDK  11.0.10 and mssql-jdbc-9.2.1.jre11
Without Database connection it working perfectly. But when I add connection string it's show me Error fill report: Erro fill internal: java.lang.NullPointerException.

Here is my database String:

```
    conn = {
        'driver': 'jdbc:sqlserver',
        'username': 'XXXX',
        'password': 'XXXX',
        'host': 'localhost',
        'database': 'XXXX',
        'jdbc_driver': 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
        'port': '1433',
        'jdbc_dir': os.path.join(DIR, 'mssql-jdbc-9.2.1.jre11.jar'),
        
    }

```

**Comment by jadsonbr** [comment]
To use the sql server database the driver must be informed as generic. Below is the documentation link with driver options.

[Doc Config.dbType](https://pyreportjasper.readthedocs.io/en/latest/api.html#Config.dbType)

Must be informed in this way

```python
    conn = {
        'driver': 'generic',
        ...
    }
```

**Comment by arif-rahman-cse** [comment]
Thank you so much. I am able to connect with SQL server .

**Comment by shwetaparashar** [comment]
Can you please write the connection that works for you.

**Comment by arif-rahman-cse** [comment]
Sure! I am using msql server. Here is my connection string.

conn = {
        'driver': 'generic',
        'username': 'username',
        'password': 'password',
        'host': 'localhost',
        'database': 'database_name',
        'port': '1433',
        'jdbc_driver': 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
        'jdbc_dir': os.path.join(DIR, 'mssql-jdbc-9.2.1.jre11.jar'),
        'jdbc_url': 'jdbc:sqlserver://localhost:1433;databaseName=Database
Name',

    }

**Comment by shwetaparashar** [comment]
Thank Arif rahman,
I wanted to go with windows authentication ,
'jdbc_url': 'jdbc:sqlserver://hostname;database=databasename;integratedSecurity=true;'

Below is the full connection details:
conn = {
'driver': 'generic',
'username': '',
'password': '',
'host': 'ERP1022DBAP01',
'database': 'RPG',
'port': '1433',
'jdbc_driver': 'com.microsoft.sqlserver.jdbc.SQLServerDriver',
'jdbc_dir': 'C:/Program Files/Microsoft JDBC Driver 6.0 for SQL Server/sqljdbc_6.0/enu/jre8/sqljdbc42.jar',
'jdbc_url': 'jdbc:sqlserver://ERP1022DBAP01:1433;databaseName=RPG;;integratedSecurity=true;',

}
I am using it but its not working
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by arif-rahman-cse** [comment]
I think problem with jdbc driver version. Please download specific version
of jdbc drive from official website
https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver15
