### ISSUE TITLE
NameError: Error fill report: Erro fill internal: java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required

### ISSUE THREAD

**Issue by CrabQ** [acesseonline/pyreportjasper#93]
**Describe the bug**
I am getting this error when try to connect pyreportjasper to msyql(5.1.73).
I am use your template ["pyreportjasper-mysql-1"](https://replit.com/@JadsonRibeiro/pyreportjasper-mysql) , when i run 'mysql.jrxml' in Jaspersoft Studio, it worked.
when i run it by pyreportjasper, i get error,

**Screenshots**
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.  
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by br.com.acesseonline.classpath.ApplicationClasspath (file:/D:/program/program_code/miniconda3/envs/jasper/Lib/site-packages/pyreportjasper/libs/acesseonline-1.0.jar) to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of br.com.acesseonline.classpath.ApplicationClasspath
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
Traceback (most recent call last):
  File "c:/Users/CRAB/Desktop/pyreportjasper-mysql-1 (3)/main.py", line 39, in <module>
    mysql_to_pdf()
  File "c:/Users/CRAB/Desktop/pyreportjasper-mysql-1 (3)/main.py", line 34, in mysql_to_pdf
    pyreportjasper.process_report()
  File "D:\program\program_code\miniconda3\envs\jasper\lib\site-packages\pyreportjasper\pyreportjasper.py", line 182, in process_report
    raise error
NameError: Error fill report: Erro fill internal: java.sql.SQLNonTransientConnectionException: CLIENT_PLUGIN_AUTH is required

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python version Python 3.6.8 :: Anaconda, Inc.（miniconda)
 - Library version pyreportjasper 2.1.2
 - Java version  java version "15.0.2" 2021-01-19
 - JVM [e.g. Oracle]
 - mysql 5.1.73
 
**Jaspersoft Studio (please complete the following information):**
 - Version  6.16.0

**Additional context**
I change  [MySQL Connector/J](https://downloads.mysql.com/archives/c-j/) (from 2.0.14  to 8.0), it doesn't work
and i change jdk 11 or jdk 15 also doesn't work
and i change mysql,  it can work in mysql5.5, when mysql version lower than 5.5, pyreportjasper doesn't work.
I wonder if it doesn't support MySQL 5.1.73？thank you!

**Comment by jadsonbr** [comment]
This does not have to do with the library, but with incompatibility between the version of the jdbc driver used and the version of MySQL you are using.

**Comment by jadsonbr** [comment]
This does not have to do with the library, but with incompatibility between the version of the jdbc driver used and the version of MySQL you are using.

Research the reported error:
```
CLIENT_PLUGIN_AUTH is required
```

**Comment by CrabQ** [comment]
> This does not have to do with the library, but with incompatibility between the version of the jdbc driver used and the version of MySQL you are using.
> 
> Research the reported error:
> 
> ```
> CLIENT_PLUGIN_AUTH is required
> ```

But the odd thing is that it works at Jaspersoft Studio, but not pyreportjasper.
I search the error in google, All the answers are to change the version of  jdbc driver, but I've tried none of them to work.
now i change the version of mysql .
thank you
