### ISSUE TITLE
Resource in subdirectory not found only in Windows Environment

### ISSUE THREAD

**Issue by tobecwb** [acesseonline/pyreportjasper#99]
**Describe the bug**
If the report use a resource on a subdirectory, like "/images/foo.jpg", the process to output the report as PDF (or compile to .jasper) show a error with a message like: "Error fill report: Erro fill internal: .net.sf.jasperreports.engine.JRException: Byte data not found at: /images/foo.jpg".
This occur only on Windows environment.

**To Reproduce**
1. Create a report with resources on a subdirectory.
2. Process or compile the report

**Expected behavior**
No error if resource file is available on correct location

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.85
 - Library version 2.1.2
 - Java version 15.0.1
 - OpenJDK

**Jaspersoft Studio (please complete the following information):**
 - Version 6.16.0

**Additional context**
If I manually edit the .jrxml file, looking for the `<imageExpression>` and change the path separator, the report works correctly.

Example:
search for:
`<imageExpression><![CDATA["/images/foo.jpg"]]></imageExpression>`

replace to:
`<imageExpression><![CDATA["\\images\\foo.jpg"]]></imageExpression>`

**Comment by jadsonbr** [comment]
Example of using images

[https://replit.com/@JadsonRibeiro/with-image-pyreportjasper#main.py](https://replit.com/@JadsonRibeiro/with-image-pyreportjasper#main.py)

**Comment by tobecwb** [comment]
> Example of using images
> 
> https://replit.com/@JadsonRibeiro/with-image-pyreportjasper#main.py
> 
> You need to add the directory where the image is located in the `resource `parameter
> 
> And put in the report only the name of the file with the extension
> `<imageExpression><![CDATA["logo-pyreportjasper.png"]]></imageExpression>`

> Example of using images
> 
> https://replit.com/@JadsonRibeiro/with-image-pyreportjasper#main.py

the problem was not using image!
This is working correctly.
**The problem is using image on a subdirectory on windows environment.**

In your example, the jrxml was referencing the image is on the same directory.

Try the following directory structure:
- report.jrxml
- images\logo-pyreportjasper.png

and change the report.jrxml, on imageExpression value to `<![CDATA["/images/logo-pyreportjasper.png"]]>` (this is the way that Jasper Studio set the value).

If you export to PDF with pyreportjasper on a Linux Environment, this will work, but on Windows Environment, this will throw a error.

**Comment by jadsonbr** [comment]
Just enter the full path in the resource parameter

Let's assume that the directory where your images are located is: `C:\Users\<UserName>\Pictures`

```python
import os
from pyreportjasper import PyReportJasper


def contains_image():
   REPORTS_DIR = os.path.abspath(os.path.dirname(__file__))
   input_file = os.path.join(REPORTS_DIR, 'with_image.jrxml')
   output_file = os.path.join(REPORTS_DIR, 'report')
   pyreportjasper = PyReportJasper()
   pyreportjasper.config(
      input_file,
      output_file,
      output_formats=["pdf"],
      db_connection={},
      resource="C:\Users\<UserName>\Pictures"
   )
   pyreportjasper.process_report()
   print('Result is the file below.')
   print(output_file + '.pdf')
```

And in your jrxml you just need to put the name of the image
`<imageExpression><![CDATA["foo.jpg"]]></imageExpression>`

**Comment by tobecwb** [comment]
> Just enter the full path in the resource parameter
> 
> Let's assume that the directory where your images are located is: `C:\Users\<UserName>\Pictures`
> 
> ```python
> import os
> from pyreportjasper import PyReportJasper
> 
> 
> def contains_image():
>    REPORTS_DIR = os.path.abspath(os.path.dirname(__file__))
>    input_file = os.path.join(REPORTS_DIR, 'with_image.jrxml')
>    output_file = os.path.join(REPORTS_DIR, 'report')
>    pyreportjasper = PyReportJasper()
>    pyreportjasper.config(
>       input_file,
>       output_file,
>       output_formats=["pdf"],
>       db_connection={},
>       resource="C:\Users\<UserName>\Pictures"
>    )
>    pyreportjasper.process_report()
>    print('Result is the file below.')
>    print(output_file + '.pdf')
> ```
> 
> And in your jrxml you just need to put the name of the image
> `<imageExpression><![CDATA["foo.jpg"]]></imageExpression>`

tks, 
but this bring some problems on Jasper Studio (image don't show on Preview).
If my project has several reports, I will have to edit one by one.

for now, i am manually replacing path in jrxml in the project.
In the end, it will run on a Linux server
